//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbmsSoapServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="DbmsSoap", ConfigurationName="DbmsSoapServiceReference.Application")]
    public interface Application
    {
        
        // CODEGEN: Generating message contract since the operation CreateDatabase is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="CreateDatabase", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DbmsSoapServiceReference.CreateDatabaseResponse1 CreateDatabase(DbmsSoapServiceReference.CreateDatabase1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="CreateDatabase", ReplyAction="*")]
        System.Threading.Tasks.Task<DbmsSoapServiceReference.CreateDatabaseResponse1> CreateDatabaseAsync(DbmsSoapServiceReference.CreateDatabase1 request);
        
        // CODEGEN: Generating message contract since the operation GetDatabase is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="GetDatabase", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DbmsSoapServiceReference.GetDatabaseResponse1 GetDatabase(DbmsSoapServiceReference.GetDatabase1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetDatabase", ReplyAction="*")]
        System.Threading.Tasks.Task<DbmsSoapServiceReference.GetDatabaseResponse1> GetDatabaseAsync(DbmsSoapServiceReference.GetDatabase1 request);
        
        // CODEGEN: Generating message contract since the operation DeleteDatabase is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="DeleteDatabase", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DbmsSoapServiceReference.DeleteDatabaseResponse1 DeleteDatabase(DbmsSoapServiceReference.DeleteDatabase1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DeleteDatabase", ReplyAction="*")]
        System.Threading.Tasks.Task<DbmsSoapServiceReference.DeleteDatabaseResponse1> DeleteDatabaseAsync(DbmsSoapServiceReference.DeleteDatabase1 request);
        
        // CODEGEN: Generating message contract since the operation AddTable is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="AddTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DbmsSoapServiceReference.AddTableResponse1 AddTable(DbmsSoapServiceReference.AddTable1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AddTable", ReplyAction="*")]
        System.Threading.Tasks.Task<DbmsSoapServiceReference.AddTableResponse1> AddTableAsync(DbmsSoapServiceReference.AddTable1 request);
        
        // CODEGEN: Generating message contract since the operation RemoveTable is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="RemoveTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DbmsSoapServiceReference.RemoveTableResponse1 RemoveTable(DbmsSoapServiceReference.RemoveTable1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="RemoveTable", ReplyAction="*")]
        System.Threading.Tasks.Task<DbmsSoapServiceReference.RemoveTableResponse1> RemoveTableAsync(DbmsSoapServiceReference.RemoveTable1 request);
        
        // CODEGEN: Generating message contract since the operation GetTable is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="GetTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DbmsSoapServiceReference.GetTableResponse1 GetTable(DbmsSoapServiceReference.GetTable1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetTable", ReplyAction="*")]
        System.Threading.Tasks.Task<DbmsSoapServiceReference.GetTableResponse1> GetTableAsync(DbmsSoapServiceReference.GetTable1 request);
        
        // CODEGEN: Generating message contract since the operation AddRow is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="AddRow", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DbmsSoapServiceReference.AddRowResponse1 AddRow(DbmsSoapServiceReference.AddRow1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AddRow", ReplyAction="*")]
        System.Threading.Tasks.Task<DbmsSoapServiceReference.AddRowResponse1> AddRowAsync(DbmsSoapServiceReference.AddRow1 request);
        
        // CODEGEN: Generating message contract since the operation RemoveRow is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="RemoveRow", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DbmsSoapServiceReference.RemoveRowResponse1 RemoveRow(DbmsSoapServiceReference.RemoveRow1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="RemoveRow", ReplyAction="*")]
        System.Threading.Tasks.Task<DbmsSoapServiceReference.RemoveRowResponse1> RemoveRowAsync(DbmsSoapServiceReference.RemoveRow1 request);
        
        // CODEGEN: Generating message contract since the operation ValidateCell is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="ValidateCell", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DbmsSoapServiceReference.ValidateCellResponse1 ValidateCell(DbmsSoapServiceReference.ValidateCell1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ValidateCell", ReplyAction="*")]
        System.Threading.Tasks.Task<DbmsSoapServiceReference.ValidateCellResponse1> ValidateCellAsync(DbmsSoapServiceReference.ValidateCell1 request);
        
        // CODEGEN: Generating message contract since the operation UpdateCell is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="UpdateCell", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DbmsSoapServiceReference.UpdateCellResponse1 UpdateCell(DbmsSoapServiceReference.UpdateCell1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="UpdateCell", ReplyAction="*")]
        System.Threading.Tasks.Task<DbmsSoapServiceReference.UpdateCellResponse1> UpdateCellAsync(DbmsSoapServiceReference.UpdateCell1 request);
        
        // CODEGEN: Generating message contract since the operation GetTableDifference is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="GetTableDifference", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DbmsSoapServiceReference.GetTableDifferenceResponse1 GetTableDifference(DbmsSoapServiceReference.GetTableDifference1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetTableDifference", ReplyAction="*")]
        System.Threading.Tasks.Task<DbmsSoapServiceReference.GetTableDifferenceResponse1> GetTableDifferenceAsync(DbmsSoapServiceReference.GetTableDifference1 request);
        
        // CODEGEN: Generating message contract since the operation TableExists is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="TableExists", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DbmsSoapServiceReference.TableExistsResponse1 TableExists(DbmsSoapServiceReference.TableExists1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="TableExists", ReplyAction="*")]
        System.Threading.Tasks.Task<DbmsSoapServiceReference.TableExistsResponse1> TableExistsAsync(DbmsSoapServiceReference.TableExists1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="DbmsSoap")]
    public partial class CreateDatabase
    {
        
        private string dbNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DbName
        {
            get
            {
                return this.dbNameField;
            }
            set
            {
                this.dbNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="DbmsSoap")]
    public partial class TableExistsResponse
    {
        
        private bool tableExistsResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool TableExistsResult
        {
            get
            {
                return this.tableExistsResultField;
            }
            set
            {
                this.tableExistsResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="DbmsSoap")]
    public partial class TableExists
    {
        
        private string dbNameField;
        
        private int tableIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DbName
        {
            get
            {
                return this.dbNameField;
            }
            set
            {
                this.dbNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int TableId
        {
            get
            {
                return this.tableIdField;
            }
            set
            {
                this.tableIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="DbmsSoap")]
    public partial class GetTableDifferenceResponse
    {
        
        private Table getTableDifferenceResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Table GetTableDifferenceResult
        {
            get
            {
                return this.getTableDifferenceResultField;
            }
            set
            {
                this.getTableDifferenceResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Messages")]
    public partial class Table
    {
        
        private int idField;
        
        private string nameField;
        
        private Column[] columnsField;
        
        private Row[] rowsField;
        
        private bool is_table_differenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Column[] columns
        {
            get
            {
                return this.columnsField;
            }
            set
            {
                this.columnsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Row[] rows
        {
            get
            {
                return this.rowsField;
            }
            set
            {
                this.rowsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool is_table_difference
        {
            get
            {
                return this.is_table_differenceField;
            }
            set
            {
                this.is_table_differenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Messages")]
    public partial class Column
    {
        
        private string nameField;
        
        private Type typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Type type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Messages")]
    public partial class Type
    {
        
        private TypeEnum type_enumField;
        
        private int r1Field;
        
        private bool r1FieldSpecified;
        
        private int r2Field;
        
        private bool r2FieldSpecified;
        
        private int g1Field;
        
        private bool g1FieldSpecified;
        
        private int g2Field;
        
        private bool g2FieldSpecified;
        
        private int b1Field;
        
        private bool b1FieldSpecified;
        
        private int b2Field;
        
        private bool b2FieldSpecified;
        
        private string to_strField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TypeEnum type_enum
        {
            get
            {
                return this.type_enumField;
            }
            set
            {
                this.type_enumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int r1
        {
            get
            {
                return this.r1Field;
            }
            set
            {
                this.r1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool r1Specified
        {
            get
            {
                return this.r1FieldSpecified;
            }
            set
            {
                this.r1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int r2
        {
            get
            {
                return this.r2Field;
            }
            set
            {
                this.r2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool r2Specified
        {
            get
            {
                return this.r2FieldSpecified;
            }
            set
            {
                this.r2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int g1
        {
            get
            {
                return this.g1Field;
            }
            set
            {
                this.g1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool g1Specified
        {
            get
            {
                return this.g1FieldSpecified;
            }
            set
            {
                this.g1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int g2
        {
            get
            {
                return this.g2Field;
            }
            set
            {
                this.g2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool g2Specified
        {
            get
            {
                return this.g2FieldSpecified;
            }
            set
            {
                this.g2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int b1
        {
            get
            {
                return this.b1Field;
            }
            set
            {
                this.b1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool b1Specified
        {
            get
            {
                return this.b1FieldSpecified;
            }
            set
            {
                this.b1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int b2
        {
            get
            {
                return this.b2Field;
            }
            set
            {
                this.b2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool b2Specified
        {
            get
            {
                return this.b2FieldSpecified;
            }
            set
            {
                this.b2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string to_str
        {
            get
            {
                return this.to_strField;
            }
            set
            {
                this.to_strField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="DbmsSoap")]
    public enum TypeEnum
    {
        
        /// <remarks/>
        Char,
        
        /// <remarks/>
        Color,
        
        /// <remarks/>
        ColorInvl,
        
        /// <remarks/>
        Integer,
        
        /// <remarks/>
        Real,
        
        /// <remarks/>
        String,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Messages")]
    public partial class Row
    {
        
        private int idField;
        
        private string[] cellsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="DbmsSoap", IsNullable=false)]
        public string[] cells
        {
            get
            {
                return this.cellsField;
            }
            set
            {
                this.cellsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="DbmsSoap")]
    public partial class GetTableDifference
    {
        
        private string dbNameField;
        
        private int leftTableIdField;
        
        private int rightTableIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DbName
        {
            get
            {
                return this.dbNameField;
            }
            set
            {
                this.dbNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int LeftTableId
        {
            get
            {
                return this.leftTableIdField;
            }
            set
            {
                this.leftTableIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int RightTableId
        {
            get
            {
                return this.rightTableIdField;
            }
            set
            {
                this.rightTableIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="DbmsSoap")]
    public partial class UpdateCellResponse
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="DbmsSoap")]
    public partial class UpdateCell
    {
        
        private string dbNameField;
        
        private int tableIdField;
        
        private int rowIdField;
        
        private int columnIdField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DbName
        {
            get
            {
                return this.dbNameField;
            }
            set
            {
                this.dbNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int TableId
        {
            get
            {
                return this.tableIdField;
            }
            set
            {
                this.tableIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int RowId
        {
            get
            {
                return this.rowIdField;
            }
            set
            {
                this.rowIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int ColumnId
        {
            get
            {
                return this.columnIdField;
            }
            set
            {
                this.columnIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="DbmsSoap")]
    public partial class ValidateCellResponse
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="DbmsSoap")]
    public partial class ValidateCell
    {
        
        private string dbNameField;
        
        private int tableIdField;
        
        private int columnIdField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DbName
        {
            get
            {
                return this.dbNameField;
            }
            set
            {
                this.dbNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int TableId
        {
            get
            {
                return this.tableIdField;
            }
            set
            {
                this.tableIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ColumnId
        {
            get
            {
                return this.columnIdField;
            }
            set
            {
                this.columnIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="DbmsSoap")]
    public partial class RemoveRowResponse
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="DbmsSoap")]
    public partial class RemoveRow
    {
        
        private string dbNameField;
        
        private int tableIdField;
        
        private int rowIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DbName
        {
            get
            {
                return this.dbNameField;
            }
            set
            {
                this.dbNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int TableId
        {
            get
            {
                return this.tableIdField;
            }
            set
            {
                this.tableIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int RowId
        {
            get
            {
                return this.rowIdField;
            }
            set
            {
                this.rowIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="DbmsSoap")]
    public partial class AddRowResponse
    {
        
        private int addRowResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int AddRowResult
        {
            get
            {
                return this.addRowResultField;
            }
            set
            {
                this.addRowResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="DbmsSoap")]
    public partial class AddRow
    {
        
        private string dbNameField;
        
        private int tableIdField;
        
        private string[] cellsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DbName
        {
            get
            {
                return this.dbNameField;
            }
            set
            {
                this.dbNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int TableId
        {
            get
            {
                return this.tableIdField;
            }
            set
            {
                this.tableIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public string[] Cells
        {
            get
            {
                return this.cellsField;
            }
            set
            {
                this.cellsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="DbmsSoap")]
    public partial class GetTableResponse
    {
        
        private Table getTableResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Table GetTableResult
        {
            get
            {
                return this.getTableResultField;
            }
            set
            {
                this.getTableResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="DbmsSoap")]
    public partial class GetTable
    {
        
        private string dbNameField;
        
        private int tableIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DbName
        {
            get
            {
                return this.dbNameField;
            }
            set
            {
                this.dbNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int TableId
        {
            get
            {
                return this.tableIdField;
            }
            set
            {
                this.tableIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="DbmsSoap")]
    public partial class RemoveTableResponse
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="DbmsSoap")]
    public partial class RemoveTable
    {
        
        private string dbNameField;
        
        private int tableIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DbName
        {
            get
            {
                return this.dbNameField;
            }
            set
            {
                this.dbNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int TableId
        {
            get
            {
                return this.tableIdField;
            }
            set
            {
                this.tableIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="DbmsSoap")]
    public partial class AddTableResponse
    {
        
        private System.Nullable<int> addTableResultField;
        
        private bool addTableResultFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> AddTableResult
        {
            get
            {
                return this.addTableResultField;
            }
            set
            {
                this.addTableResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AddTableResultSpecified
        {
            get
            {
                return this.addTableResultFieldSpecified;
            }
            set
            {
                this.addTableResultFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="DbmsSoap")]
    public partial class AddTable
    {
        
        private string dbNameField;
        
        private string tableNameField;
        
        private Column[] columnsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DbName
        {
            get
            {
                return this.dbNameField;
            }
            set
            {
                this.dbNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TableName
        {
            get
            {
                return this.tableNameField;
            }
            set
            {
                this.tableNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="Messages", IsNullable=false)]
        public Column[] Columns
        {
            get
            {
                return this.columnsField;
            }
            set
            {
                this.columnsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="DbmsSoap")]
    public partial class DeleteDatabaseResponse
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="DbmsSoap")]
    public partial class DeleteDatabase
    {
        
        private string dbNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DbName
        {
            get
            {
                return this.dbNameField;
            }
            set
            {
                this.dbNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Messages")]
    public partial class TableInfo
    {
        
        private int idField;
        
        private string nameField;
        
        private int left_table_idField;
        
        private bool left_table_idFieldSpecified;
        
        private int right_table_idField;
        
        private bool right_table_idFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int left_table_id
        {
            get
            {
                return this.left_table_idField;
            }
            set
            {
                this.left_table_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool left_table_idSpecified
        {
            get
            {
                return this.left_table_idFieldSpecified;
            }
            set
            {
                this.left_table_idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int right_table_id
        {
            get
            {
                return this.right_table_idField;
            }
            set
            {
                this.right_table_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool right_table_idSpecified
        {
            get
            {
                return this.right_table_idFieldSpecified;
            }
            set
            {
                this.right_table_idFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Messages")]
    public partial class DatabaseInfo
    {
        
        private TableInfo[] tablesField;
        
        private TableInfo[] table_differencesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TableInfo[] tables
        {
            get
            {
                return this.tablesField;
            }
            set
            {
                this.tablesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TableInfo[] table_differences
        {
            get
            {
                return this.table_differencesField;
            }
            set
            {
                this.table_differencesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="DbmsSoap")]
    public partial class GetDatabaseResponse
    {
        
        private DatabaseInfo getDatabaseResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DatabaseInfo GetDatabaseResult
        {
            get
            {
                return this.getDatabaseResultField;
            }
            set
            {
                this.getDatabaseResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="DbmsSoap")]
    public partial class GetDatabase
    {
        
        private string dbNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DbName
        {
            get
            {
                return this.dbNameField;
            }
            set
            {
                this.dbNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="DbmsSoap")]
    public partial class CreateDatabaseResponse
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateDatabase1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DbmsSoap", Order=0)]
        public DbmsSoapServiceReference.CreateDatabase CreateDatabase;
        
        public CreateDatabase1()
        {
        }
        
        public CreateDatabase1(DbmsSoapServiceReference.CreateDatabase CreateDatabase)
        {
            this.CreateDatabase = CreateDatabase;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateDatabaseResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DbmsSoap", Order=0)]
        public DbmsSoapServiceReference.CreateDatabaseResponse CreateDatabaseResponse;
        
        public CreateDatabaseResponse1()
        {
        }
        
        public CreateDatabaseResponse1(DbmsSoapServiceReference.CreateDatabaseResponse CreateDatabaseResponse)
        {
            this.CreateDatabaseResponse = CreateDatabaseResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDatabase1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DbmsSoap", Order=0)]
        public DbmsSoapServiceReference.GetDatabase GetDatabase;
        
        public GetDatabase1()
        {
        }
        
        public GetDatabase1(DbmsSoapServiceReference.GetDatabase GetDatabase)
        {
            this.GetDatabase = GetDatabase;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDatabaseResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DbmsSoap", Order=0)]
        public DbmsSoapServiceReference.GetDatabaseResponse GetDatabaseResponse;
        
        public GetDatabaseResponse1()
        {
        }
        
        public GetDatabaseResponse1(DbmsSoapServiceReference.GetDatabaseResponse GetDatabaseResponse)
        {
            this.GetDatabaseResponse = GetDatabaseResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteDatabase1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DbmsSoap", Order=0)]
        public DbmsSoapServiceReference.DeleteDatabase DeleteDatabase;
        
        public DeleteDatabase1()
        {
        }
        
        public DeleteDatabase1(DbmsSoapServiceReference.DeleteDatabase DeleteDatabase)
        {
            this.DeleteDatabase = DeleteDatabase;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteDatabaseResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DbmsSoap", Order=0)]
        public DbmsSoapServiceReference.DeleteDatabaseResponse DeleteDatabaseResponse;
        
        public DeleteDatabaseResponse1()
        {
        }
        
        public DeleteDatabaseResponse1(DbmsSoapServiceReference.DeleteDatabaseResponse DeleteDatabaseResponse)
        {
            this.DeleteDatabaseResponse = DeleteDatabaseResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTable1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DbmsSoap", Order=0)]
        public DbmsSoapServiceReference.AddTable AddTable;
        
        public AddTable1()
        {
        }
        
        public AddTable1(DbmsSoapServiceReference.AddTable AddTable)
        {
            this.AddTable = AddTable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTableResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DbmsSoap", Order=0)]
        public DbmsSoapServiceReference.AddTableResponse AddTableResponse;
        
        public AddTableResponse1()
        {
        }
        
        public AddTableResponse1(DbmsSoapServiceReference.AddTableResponse AddTableResponse)
        {
            this.AddTableResponse = AddTableResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveTable1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DbmsSoap", Order=0)]
        public DbmsSoapServiceReference.RemoveTable RemoveTable;
        
        public RemoveTable1()
        {
        }
        
        public RemoveTable1(DbmsSoapServiceReference.RemoveTable RemoveTable)
        {
            this.RemoveTable = RemoveTable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveTableResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DbmsSoap", Order=0)]
        public DbmsSoapServiceReference.RemoveTableResponse RemoveTableResponse;
        
        public RemoveTableResponse1()
        {
        }
        
        public RemoveTableResponse1(DbmsSoapServiceReference.RemoveTableResponse RemoveTableResponse)
        {
            this.RemoveTableResponse = RemoveTableResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTable1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DbmsSoap", Order=0)]
        public DbmsSoapServiceReference.GetTable GetTable;
        
        public GetTable1()
        {
        }
        
        public GetTable1(DbmsSoapServiceReference.GetTable GetTable)
        {
            this.GetTable = GetTable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTableResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DbmsSoap", Order=0)]
        public DbmsSoapServiceReference.GetTableResponse GetTableResponse;
        
        public GetTableResponse1()
        {
        }
        
        public GetTableResponse1(DbmsSoapServiceReference.GetTableResponse GetTableResponse)
        {
            this.GetTableResponse = GetTableResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRow1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DbmsSoap", Order=0)]
        public DbmsSoapServiceReference.AddRow AddRow;
        
        public AddRow1()
        {
        }
        
        public AddRow1(DbmsSoapServiceReference.AddRow AddRow)
        {
            this.AddRow = AddRow;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRowResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DbmsSoap", Order=0)]
        public DbmsSoapServiceReference.AddRowResponse AddRowResponse;
        
        public AddRowResponse1()
        {
        }
        
        public AddRowResponse1(DbmsSoapServiceReference.AddRowResponse AddRowResponse)
        {
            this.AddRowResponse = AddRowResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveRow1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DbmsSoap", Order=0)]
        public DbmsSoapServiceReference.RemoveRow RemoveRow;
        
        public RemoveRow1()
        {
        }
        
        public RemoveRow1(DbmsSoapServiceReference.RemoveRow RemoveRow)
        {
            this.RemoveRow = RemoveRow;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveRowResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DbmsSoap", Order=0)]
        public DbmsSoapServiceReference.RemoveRowResponse RemoveRowResponse;
        
        public RemoveRowResponse1()
        {
        }
        
        public RemoveRowResponse1(DbmsSoapServiceReference.RemoveRowResponse RemoveRowResponse)
        {
            this.RemoveRowResponse = RemoveRowResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateCell1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DbmsSoap", Order=0)]
        public DbmsSoapServiceReference.ValidateCell ValidateCell;
        
        public ValidateCell1()
        {
        }
        
        public ValidateCell1(DbmsSoapServiceReference.ValidateCell ValidateCell)
        {
            this.ValidateCell = ValidateCell;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateCellResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DbmsSoap", Order=0)]
        public DbmsSoapServiceReference.ValidateCellResponse ValidateCellResponse;
        
        public ValidateCellResponse1()
        {
        }
        
        public ValidateCellResponse1(DbmsSoapServiceReference.ValidateCellResponse ValidateCellResponse)
        {
            this.ValidateCellResponse = ValidateCellResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCell1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DbmsSoap", Order=0)]
        public DbmsSoapServiceReference.UpdateCell UpdateCell;
        
        public UpdateCell1()
        {
        }
        
        public UpdateCell1(DbmsSoapServiceReference.UpdateCell UpdateCell)
        {
            this.UpdateCell = UpdateCell;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCellResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DbmsSoap", Order=0)]
        public DbmsSoapServiceReference.UpdateCellResponse UpdateCellResponse;
        
        public UpdateCellResponse1()
        {
        }
        
        public UpdateCellResponse1(DbmsSoapServiceReference.UpdateCellResponse UpdateCellResponse)
        {
            this.UpdateCellResponse = UpdateCellResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTableDifference1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DbmsSoap", Order=0)]
        public DbmsSoapServiceReference.GetTableDifference GetTableDifference;
        
        public GetTableDifference1()
        {
        }
        
        public GetTableDifference1(DbmsSoapServiceReference.GetTableDifference GetTableDifference)
        {
            this.GetTableDifference = GetTableDifference;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTableDifferenceResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DbmsSoap", Order=0)]
        public DbmsSoapServiceReference.GetTableDifferenceResponse GetTableDifferenceResponse;
        
        public GetTableDifferenceResponse1()
        {
        }
        
        public GetTableDifferenceResponse1(DbmsSoapServiceReference.GetTableDifferenceResponse GetTableDifferenceResponse)
        {
            this.GetTableDifferenceResponse = GetTableDifferenceResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TableExists1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DbmsSoap", Order=0)]
        public DbmsSoapServiceReference.TableExists TableExists;
        
        public TableExists1()
        {
        }
        
        public TableExists1(DbmsSoapServiceReference.TableExists TableExists)
        {
            this.TableExists = TableExists;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TableExistsResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DbmsSoap", Order=0)]
        public DbmsSoapServiceReference.TableExistsResponse TableExistsResponse;
        
        public TableExistsResponse1()
        {
        }
        
        public TableExistsResponse1(DbmsSoapServiceReference.TableExistsResponse TableExistsResponse)
        {
            this.TableExistsResponse = TableExistsResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ApplicationChannel : DbmsSoapServiceReference.Application, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ApplicationClient : System.ServiceModel.ClientBase<DbmsSoapServiceReference.Application>, DbmsSoapServiceReference.Application
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ApplicationClient() : 
                base(ApplicationClient.GetDefaultBinding(), ApplicationClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.Application.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ApplicationClient(EndpointConfiguration endpointConfiguration) : 
                base(ApplicationClient.GetBindingForEndpoint(endpointConfiguration), ApplicationClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ApplicationClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ApplicationClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ApplicationClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ApplicationClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ApplicationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DbmsSoapServiceReference.CreateDatabaseResponse1 DbmsSoapServiceReference.Application.CreateDatabase(DbmsSoapServiceReference.CreateDatabase1 request)
        {
            return base.Channel.CreateDatabase(request);
        }
        
        public DbmsSoapServiceReference.CreateDatabaseResponse CreateDatabase(DbmsSoapServiceReference.CreateDatabase CreateDatabase1)
        {
            DbmsSoapServiceReference.CreateDatabase1 inValue = new DbmsSoapServiceReference.CreateDatabase1();
            inValue.CreateDatabase = CreateDatabase1;
            DbmsSoapServiceReference.CreateDatabaseResponse1 retVal = ((DbmsSoapServiceReference.Application)(this)).CreateDatabase(inValue);
            return retVal.CreateDatabaseResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DbmsSoapServiceReference.CreateDatabaseResponse1> DbmsSoapServiceReference.Application.CreateDatabaseAsync(DbmsSoapServiceReference.CreateDatabase1 request)
        {
            return base.Channel.CreateDatabaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<DbmsSoapServiceReference.CreateDatabaseResponse1> CreateDatabaseAsync(DbmsSoapServiceReference.CreateDatabase CreateDatabase)
        {
            DbmsSoapServiceReference.CreateDatabase1 inValue = new DbmsSoapServiceReference.CreateDatabase1();
            inValue.CreateDatabase = CreateDatabase;
            return ((DbmsSoapServiceReference.Application)(this)).CreateDatabaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DbmsSoapServiceReference.GetDatabaseResponse1 DbmsSoapServiceReference.Application.GetDatabase(DbmsSoapServiceReference.GetDatabase1 request)
        {
            return base.Channel.GetDatabase(request);
        }
        
        public DbmsSoapServiceReference.GetDatabaseResponse GetDatabase(DbmsSoapServiceReference.GetDatabase GetDatabase1)
        {
            DbmsSoapServiceReference.GetDatabase1 inValue = new DbmsSoapServiceReference.GetDatabase1();
            inValue.GetDatabase = GetDatabase1;
            DbmsSoapServiceReference.GetDatabaseResponse1 retVal = ((DbmsSoapServiceReference.Application)(this)).GetDatabase(inValue);
            return retVal.GetDatabaseResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DbmsSoapServiceReference.GetDatabaseResponse1> DbmsSoapServiceReference.Application.GetDatabaseAsync(DbmsSoapServiceReference.GetDatabase1 request)
        {
            return base.Channel.GetDatabaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<DbmsSoapServiceReference.GetDatabaseResponse1> GetDatabaseAsync(DbmsSoapServiceReference.GetDatabase GetDatabase)
        {
            DbmsSoapServiceReference.GetDatabase1 inValue = new DbmsSoapServiceReference.GetDatabase1();
            inValue.GetDatabase = GetDatabase;
            return ((DbmsSoapServiceReference.Application)(this)).GetDatabaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DbmsSoapServiceReference.DeleteDatabaseResponse1 DbmsSoapServiceReference.Application.DeleteDatabase(DbmsSoapServiceReference.DeleteDatabase1 request)
        {
            return base.Channel.DeleteDatabase(request);
        }
        
        public DbmsSoapServiceReference.DeleteDatabaseResponse DeleteDatabase(DbmsSoapServiceReference.DeleteDatabase DeleteDatabase1)
        {
            DbmsSoapServiceReference.DeleteDatabase1 inValue = new DbmsSoapServiceReference.DeleteDatabase1();
            inValue.DeleteDatabase = DeleteDatabase1;
            DbmsSoapServiceReference.DeleteDatabaseResponse1 retVal = ((DbmsSoapServiceReference.Application)(this)).DeleteDatabase(inValue);
            return retVal.DeleteDatabaseResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DbmsSoapServiceReference.DeleteDatabaseResponse1> DbmsSoapServiceReference.Application.DeleteDatabaseAsync(DbmsSoapServiceReference.DeleteDatabase1 request)
        {
            return base.Channel.DeleteDatabaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<DbmsSoapServiceReference.DeleteDatabaseResponse1> DeleteDatabaseAsync(DbmsSoapServiceReference.DeleteDatabase DeleteDatabase)
        {
            DbmsSoapServiceReference.DeleteDatabase1 inValue = new DbmsSoapServiceReference.DeleteDatabase1();
            inValue.DeleteDatabase = DeleteDatabase;
            return ((DbmsSoapServiceReference.Application)(this)).DeleteDatabaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DbmsSoapServiceReference.AddTableResponse1 DbmsSoapServiceReference.Application.AddTable(DbmsSoapServiceReference.AddTable1 request)
        {
            return base.Channel.AddTable(request);
        }
        
        public DbmsSoapServiceReference.AddTableResponse AddTable(DbmsSoapServiceReference.AddTable AddTable1)
        {
            DbmsSoapServiceReference.AddTable1 inValue = new DbmsSoapServiceReference.AddTable1();
            inValue.AddTable = AddTable1;
            DbmsSoapServiceReference.AddTableResponse1 retVal = ((DbmsSoapServiceReference.Application)(this)).AddTable(inValue);
            return retVal.AddTableResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DbmsSoapServiceReference.AddTableResponse1> DbmsSoapServiceReference.Application.AddTableAsync(DbmsSoapServiceReference.AddTable1 request)
        {
            return base.Channel.AddTableAsync(request);
        }
        
        public System.Threading.Tasks.Task<DbmsSoapServiceReference.AddTableResponse1> AddTableAsync(DbmsSoapServiceReference.AddTable AddTable)
        {
            DbmsSoapServiceReference.AddTable1 inValue = new DbmsSoapServiceReference.AddTable1();
            inValue.AddTable = AddTable;
            return ((DbmsSoapServiceReference.Application)(this)).AddTableAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DbmsSoapServiceReference.RemoveTableResponse1 DbmsSoapServiceReference.Application.RemoveTable(DbmsSoapServiceReference.RemoveTable1 request)
        {
            return base.Channel.RemoveTable(request);
        }
        
        public DbmsSoapServiceReference.RemoveTableResponse RemoveTable(DbmsSoapServiceReference.RemoveTable RemoveTable1)
        {
            DbmsSoapServiceReference.RemoveTable1 inValue = new DbmsSoapServiceReference.RemoveTable1();
            inValue.RemoveTable = RemoveTable1;
            DbmsSoapServiceReference.RemoveTableResponse1 retVal = ((DbmsSoapServiceReference.Application)(this)).RemoveTable(inValue);
            return retVal.RemoveTableResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DbmsSoapServiceReference.RemoveTableResponse1> DbmsSoapServiceReference.Application.RemoveTableAsync(DbmsSoapServiceReference.RemoveTable1 request)
        {
            return base.Channel.RemoveTableAsync(request);
        }
        
        public System.Threading.Tasks.Task<DbmsSoapServiceReference.RemoveTableResponse1> RemoveTableAsync(DbmsSoapServiceReference.RemoveTable RemoveTable)
        {
            DbmsSoapServiceReference.RemoveTable1 inValue = new DbmsSoapServiceReference.RemoveTable1();
            inValue.RemoveTable = RemoveTable;
            return ((DbmsSoapServiceReference.Application)(this)).RemoveTableAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DbmsSoapServiceReference.GetTableResponse1 DbmsSoapServiceReference.Application.GetTable(DbmsSoapServiceReference.GetTable1 request)
        {
            return base.Channel.GetTable(request);
        }
        
        public DbmsSoapServiceReference.GetTableResponse GetTable(DbmsSoapServiceReference.GetTable GetTable1)
        {
            DbmsSoapServiceReference.GetTable1 inValue = new DbmsSoapServiceReference.GetTable1();
            inValue.GetTable = GetTable1;
            DbmsSoapServiceReference.GetTableResponse1 retVal = ((DbmsSoapServiceReference.Application)(this)).GetTable(inValue);
            return retVal.GetTableResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DbmsSoapServiceReference.GetTableResponse1> DbmsSoapServiceReference.Application.GetTableAsync(DbmsSoapServiceReference.GetTable1 request)
        {
            return base.Channel.GetTableAsync(request);
        }
        
        public System.Threading.Tasks.Task<DbmsSoapServiceReference.GetTableResponse1> GetTableAsync(DbmsSoapServiceReference.GetTable GetTable)
        {
            DbmsSoapServiceReference.GetTable1 inValue = new DbmsSoapServiceReference.GetTable1();
            inValue.GetTable = GetTable;
            return ((DbmsSoapServiceReference.Application)(this)).GetTableAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DbmsSoapServiceReference.AddRowResponse1 DbmsSoapServiceReference.Application.AddRow(DbmsSoapServiceReference.AddRow1 request)
        {
            return base.Channel.AddRow(request);
        }
        
        public DbmsSoapServiceReference.AddRowResponse AddRow(DbmsSoapServiceReference.AddRow AddRow1)
        {
            DbmsSoapServiceReference.AddRow1 inValue = new DbmsSoapServiceReference.AddRow1();
            inValue.AddRow = AddRow1;
            DbmsSoapServiceReference.AddRowResponse1 retVal = ((DbmsSoapServiceReference.Application)(this)).AddRow(inValue);
            return retVal.AddRowResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DbmsSoapServiceReference.AddRowResponse1> DbmsSoapServiceReference.Application.AddRowAsync(DbmsSoapServiceReference.AddRow1 request)
        {
            return base.Channel.AddRowAsync(request);
        }
        
        public System.Threading.Tasks.Task<DbmsSoapServiceReference.AddRowResponse1> AddRowAsync(DbmsSoapServiceReference.AddRow AddRow)
        {
            DbmsSoapServiceReference.AddRow1 inValue = new DbmsSoapServiceReference.AddRow1();
            inValue.AddRow = AddRow;
            return ((DbmsSoapServiceReference.Application)(this)).AddRowAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DbmsSoapServiceReference.RemoveRowResponse1 DbmsSoapServiceReference.Application.RemoveRow(DbmsSoapServiceReference.RemoveRow1 request)
        {
            return base.Channel.RemoveRow(request);
        }
        
        public DbmsSoapServiceReference.RemoveRowResponse RemoveRow(DbmsSoapServiceReference.RemoveRow RemoveRow1)
        {
            DbmsSoapServiceReference.RemoveRow1 inValue = new DbmsSoapServiceReference.RemoveRow1();
            inValue.RemoveRow = RemoveRow1;
            DbmsSoapServiceReference.RemoveRowResponse1 retVal = ((DbmsSoapServiceReference.Application)(this)).RemoveRow(inValue);
            return retVal.RemoveRowResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DbmsSoapServiceReference.RemoveRowResponse1> DbmsSoapServiceReference.Application.RemoveRowAsync(DbmsSoapServiceReference.RemoveRow1 request)
        {
            return base.Channel.RemoveRowAsync(request);
        }
        
        public System.Threading.Tasks.Task<DbmsSoapServiceReference.RemoveRowResponse1> RemoveRowAsync(DbmsSoapServiceReference.RemoveRow RemoveRow)
        {
            DbmsSoapServiceReference.RemoveRow1 inValue = new DbmsSoapServiceReference.RemoveRow1();
            inValue.RemoveRow = RemoveRow;
            return ((DbmsSoapServiceReference.Application)(this)).RemoveRowAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DbmsSoapServiceReference.ValidateCellResponse1 DbmsSoapServiceReference.Application.ValidateCell(DbmsSoapServiceReference.ValidateCell1 request)
        {
            return base.Channel.ValidateCell(request);
        }
        
        public DbmsSoapServiceReference.ValidateCellResponse ValidateCell(DbmsSoapServiceReference.ValidateCell ValidateCell1)
        {
            DbmsSoapServiceReference.ValidateCell1 inValue = new DbmsSoapServiceReference.ValidateCell1();
            inValue.ValidateCell = ValidateCell1;
            DbmsSoapServiceReference.ValidateCellResponse1 retVal = ((DbmsSoapServiceReference.Application)(this)).ValidateCell(inValue);
            return retVal.ValidateCellResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DbmsSoapServiceReference.ValidateCellResponse1> DbmsSoapServiceReference.Application.ValidateCellAsync(DbmsSoapServiceReference.ValidateCell1 request)
        {
            return base.Channel.ValidateCellAsync(request);
        }
        
        public System.Threading.Tasks.Task<DbmsSoapServiceReference.ValidateCellResponse1> ValidateCellAsync(DbmsSoapServiceReference.ValidateCell ValidateCell)
        {
            DbmsSoapServiceReference.ValidateCell1 inValue = new DbmsSoapServiceReference.ValidateCell1();
            inValue.ValidateCell = ValidateCell;
            return ((DbmsSoapServiceReference.Application)(this)).ValidateCellAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DbmsSoapServiceReference.UpdateCellResponse1 DbmsSoapServiceReference.Application.UpdateCell(DbmsSoapServiceReference.UpdateCell1 request)
        {
            return base.Channel.UpdateCell(request);
        }
        
        public DbmsSoapServiceReference.UpdateCellResponse UpdateCell(DbmsSoapServiceReference.UpdateCell UpdateCell1)
        {
            DbmsSoapServiceReference.UpdateCell1 inValue = new DbmsSoapServiceReference.UpdateCell1();
            inValue.UpdateCell = UpdateCell1;
            DbmsSoapServiceReference.UpdateCellResponse1 retVal = ((DbmsSoapServiceReference.Application)(this)).UpdateCell(inValue);
            return retVal.UpdateCellResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DbmsSoapServiceReference.UpdateCellResponse1> DbmsSoapServiceReference.Application.UpdateCellAsync(DbmsSoapServiceReference.UpdateCell1 request)
        {
            return base.Channel.UpdateCellAsync(request);
        }
        
        public System.Threading.Tasks.Task<DbmsSoapServiceReference.UpdateCellResponse1> UpdateCellAsync(DbmsSoapServiceReference.UpdateCell UpdateCell)
        {
            DbmsSoapServiceReference.UpdateCell1 inValue = new DbmsSoapServiceReference.UpdateCell1();
            inValue.UpdateCell = UpdateCell;
            return ((DbmsSoapServiceReference.Application)(this)).UpdateCellAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DbmsSoapServiceReference.GetTableDifferenceResponse1 DbmsSoapServiceReference.Application.GetTableDifference(DbmsSoapServiceReference.GetTableDifference1 request)
        {
            return base.Channel.GetTableDifference(request);
        }
        
        public DbmsSoapServiceReference.GetTableDifferenceResponse GetTableDifference(DbmsSoapServiceReference.GetTableDifference GetTableDifference1)
        {
            DbmsSoapServiceReference.GetTableDifference1 inValue = new DbmsSoapServiceReference.GetTableDifference1();
            inValue.GetTableDifference = GetTableDifference1;
            DbmsSoapServiceReference.GetTableDifferenceResponse1 retVal = ((DbmsSoapServiceReference.Application)(this)).GetTableDifference(inValue);
            return retVal.GetTableDifferenceResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DbmsSoapServiceReference.GetTableDifferenceResponse1> DbmsSoapServiceReference.Application.GetTableDifferenceAsync(DbmsSoapServiceReference.GetTableDifference1 request)
        {
            return base.Channel.GetTableDifferenceAsync(request);
        }
        
        public System.Threading.Tasks.Task<DbmsSoapServiceReference.GetTableDifferenceResponse1> GetTableDifferenceAsync(DbmsSoapServiceReference.GetTableDifference GetTableDifference)
        {
            DbmsSoapServiceReference.GetTableDifference1 inValue = new DbmsSoapServiceReference.GetTableDifference1();
            inValue.GetTableDifference = GetTableDifference;
            return ((DbmsSoapServiceReference.Application)(this)).GetTableDifferenceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DbmsSoapServiceReference.TableExistsResponse1 DbmsSoapServiceReference.Application.TableExists(DbmsSoapServiceReference.TableExists1 request)
        {
            return base.Channel.TableExists(request);
        }
        
        public DbmsSoapServiceReference.TableExistsResponse TableExists(DbmsSoapServiceReference.TableExists TableExists1)
        {
            DbmsSoapServiceReference.TableExists1 inValue = new DbmsSoapServiceReference.TableExists1();
            inValue.TableExists = TableExists1;
            DbmsSoapServiceReference.TableExistsResponse1 retVal = ((DbmsSoapServiceReference.Application)(this)).TableExists(inValue);
            return retVal.TableExistsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DbmsSoapServiceReference.TableExistsResponse1> DbmsSoapServiceReference.Application.TableExistsAsync(DbmsSoapServiceReference.TableExists1 request)
        {
            return base.Channel.TableExistsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DbmsSoapServiceReference.TableExistsResponse1> TableExistsAsync(DbmsSoapServiceReference.TableExists TableExists)
        {
            DbmsSoapServiceReference.TableExists1 inValue = new DbmsSoapServiceReference.TableExists1();
            inValue.TableExists = TableExists;
            return ((DbmsSoapServiceReference.Application)(this)).TableExistsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Application))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Application))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8000/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ApplicationClient.GetBindingForEndpoint(EndpointConfiguration.Application);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ApplicationClient.GetEndpointAddress(EndpointConfiguration.Application);
        }
        
        public enum EndpointConfiguration
        {
            
            Application,
        }
    }
}
